#!/usr/bin/env php
<?php

/*
 * Exit codes:
 *  0 - Success
 *  1 - Unknown
 *  2 - Incorrect amount of arguments
 *  3 - Invalid Command
 */
require_once 'vendor/autoload.php';

$isProd = false;

if ($argc < 2) {
    print 'Incorrect amount of arguments / command declaration';
    exit(2);
}

// Don't need the first element.
$_ = array_shift($argv);
$cmd = (new \SCF\Application($argv))
    ->run($isProd); 


