#!/usr/bin/env php
<?php

/*
 * Exit codes:
 *  0 - Success
 *  1 - Unknown
 *  2 - Incorrect amount of arguments
 *  3 - Invalid Command
 */
require_once 'vendor/autoload.php';

use App\Kernel;
use SCF\CommandApplication;

$isProd = false;

if ($argc < 2) {
    print 'Incorrect amount of arguments / command declaration';
    exit(2);
}

$env = [];
if (file_exists('.env')) {
    $fp = fopen('.env', 'r');
    $contents = fread($fp, filesize('.env'));
    fclose($fp);
    $unparsed = explode("\n", $contents);
    foreach ($unparsed as $keyValueStr) {
        list($key, $value) = explode('=', $keyValueStr);
        $env[$key] = $value;
    }

    unset($unparsed, $contents);
} else {
    print 'Missing .env file.. Application will still run unless your application depends on it.';
}

$config = [];
include 'config/config.php';

// First element is irrelivant to us.
$_ = array_shift($argv);
$kernel = new Kernel();
$cmd = (new CommandApplication($argv, $env, $config))
    ->run($kernel, $isProd); 


